# Generated by Django 2.2.1 on 2019-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Brand Name')),
            ],
        ),
        migrations.CreateModel(
            name='IndexedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Indexed Site')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product Name')),
                ('brand', models.ForeignKey(on_delete=None, related_name='brand', to='web.Brand')),
            ],
            options={
                'unique_together': {('title', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_number', models.PositiveIntegerField()),
                ('position_on_page', models.PositiveIntegerField()),
                ('count_of_products_on_page', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('has_discount', models.BooleanField(default=False)),
                ('price_with_discount', models.FloatField(blank=True, null=True)),
                ('img_addr', models.CharField(default='/img/default.png', max_length=1000)),
                ('indexedSite', models.ForeignKey(on_delete=None, related_name='indexedSite', to='web.IndexedSite')),
                ('product', models.ForeignKey(on_delete=None, related_name='productPositions', to='web.Product')),
            ],
        ),
    ]
