# Generated by Django 2.2.1 on 2019-06-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190601_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productposition',
            unique_together={('categories', 'page_number', 'position_on_page', 'count_of_products_on_page', 'indexedSite', 'product', 'indexedSite', 'price', 'has_discount')},
        ),
    ]
